// Mocks generated by Mockito 5.4.3-wip from annotations
// in chrome_extension_generator/test/omaha_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import '../../tool/generator/download/simple_http_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SimpleHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimpleHttpClient extends _i1.Mock implements _i2.SimpleHttpClient {
  MockSimpleHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getHtmlAtUri(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #getHtmlAtUri,
          [uri],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
